import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { createDtsCode, generateDts, resolveDtsPath, writeDts } from '../src/dts'

let dir: string

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), 'vue-layouts-dts-'))
})

afterEach(async () => {
  await rm(dir, { recursive: true, force: true })
})

describe('resolveDtsPath', () => {
  it('is undefined when disabled', () => {
    expect(resolveDtsPath(undefined, '/root')).toBeUndefined()
    expect(resolveDtsPath(false, '/root')).toBeUndefined()
  })

  it('defaults to layouts.d.ts in the root', () => {
    expect(resolveDtsPath(true, '/root')).toBe(resolve('/root', 'layouts.d.ts'))
  })

  it('resolves a custom path against the root', () => {
    expect(resolveDtsPath('types/layouts.d.ts', '/root')).toBe(resolve('/root', 'types/layouts.d.ts'))
  })
})

describe('createDtsCode', () => {
  it('renders the registry augmentation', () => {
    expect(createDtsCode(['default', 'admin'])).toMatchInlineSnapshot(`
      "/* eslint-disable */
      /* prettier-ignore */
      // Generated by vite-plugin-vue-layouts-next. Do not edit.
      export {}

      declare module 'vite-plugin-vue-layouts-next/runtime' {
        interface LayoutRegistry {
          "admin": unknown
          "default": unknown
        }
      }
      "
    `)
  })

  it('sorts and de-duplicates names', () => {
    const code = createDtsCode(['b', 'a', 'b'])
    expect(code.indexOf('"a"')).toBeLessThan(code.indexOf('"b"'))
    expect(code.match(/"b"/g)).toHaveLength(1)
  })

  it('renders an empty interface without layouts', () => {
    expect(createDtsCode([])).toContain('  interface LayoutRegistry {\n  }')
  })
})

describe('writeDts', () => {
  it('creates the file and missing parent directories', async () => {
    const path = join(dir, 'types', 'layouts.d.ts')
    expect(await writeDts(path, 'code')).toBe(true)
    expect(await readFile(path, 'utf8')).toBe('code')
  })

  it('skips the write when the content is unchanged', async () => {
    const path = join(dir, 'layouts.d.ts')
    await writeDts(path, 'code')
    expect(await writeDts(path, 'code')).toBe(false)
    expect(await writeDts(path, 'other')).toBe(true)
  })
})

describe('generateDts', () => {
  it('writes the rendered code', async () => {
    const path = join(dir, 'layouts.d.ts')
    await generateDts(path, ['default'], { warn: vi.fn() })
    expect(await readFile(path, 'utf8')).toBe(createDtsCode(['default']))
  })

  it('warns instead of throwing when the file cannot be written', async () => {
    const blocker = join(dir, 'blocker')
    await writeFile(blocker, '')
    const logger = { warn: vi.fn() }
    await expect(generateDts(join(blocker, 'layouts.d.ts'), ['default'], logger)).resolves.toBeUndefined()
    expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('layouts.d.ts'))
  })
})
