/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'name-override': RouteRecordInfo<
      'name-override',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'who-me-override': RouteRecordInfo<
      'who-me-override',
      '/about/who/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deep/': RouteRecordInfo<
      '/deep/',
      '/deep',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deep/deeper/': RouteRecordInfo<
      '/deep/deeper/',
      '/deep/deeper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deep/deeper/deepest/': RouteRecordInfo<
      '/deep/deeper/deepest/',
      '/deep/deeper/deepest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inherit/[id]': RouteRecordInfo<
      '/inherit/[id]',
      '/inherit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/inherit/deep/[id]': RouteRecordInfo<
      '/inherit/deep/[id]',
      '/inherit/deep/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/module1': RouteRecordInfo<
      '/module1',
      '/module1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/module2': RouteRecordInfo<
      '/module2',
      '/module2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news': RouteRecordInfo<
      '/news',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | '/news/'
      | 'named-news-page'
    >,
    '/news/': RouteRecordInfo<
      '/news/',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'named-news-page': RouteRecordInfo<
      'named-news-page',
      '/news/Today',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nolayout': RouteRecordInfo<
      '/nolayout',
      '/nolayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/second/': RouteRecordInfo<
      '/second/',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sublayout': RouteRecordInfo<
      '/sublayout',
      '/sublayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'name-override'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/about/index.vue': {
      routes:
        | '/about/'
      views:
        | never
    }
    'src/pages/about/who/me.vue': {
      routes:
        | 'who-me-override'
      views:
        | never
    }
    'src/pages/deep/index.vue': {
      routes:
        | '/deep/'
      views:
        | never
    }
    'src/pages/deep/deeper/index.vue': {
      routes:
        | '/deep/deeper/'
      views:
        | never
    }
    'src/pages/deep/deeper/deepest/index.vue': {
      routes:
        | '/deep/deeper/deepest/'
      views:
        | never
    }
    'src/pages/inherit/[id].vue': {
      routes:
        | '/inherit/[id]'
      views:
        | never
    }
    'src/pages/inherit/deep/[id].vue': {
      routes:
        | '/inherit/deep/[id]'
      views:
        | never
    }
    'src/pages/module1.vue': {
      routes:
        | '/module1'
      views:
        | never
    }
    'src/pages/module2.vue': {
      routes:
        | '/module2'
      views:
        | never
    }
    'src/pages/news.vue': {
      routes:
        | '/news'
        | '/news/'
        | 'named-news-page'
      views:
        | 'default'
    }
    'src/pages/news/index.vue': {
      routes:
        | '/news/'
      views:
        | never
    }
    'src/pages/news/Today.vue': {
      routes:
        | 'named-news-page'
      views:
        | never
    }
    'src/pages/nolayout.vue': {
      routes:
        | '/nolayout'
      views:
        | never
    }
    'src/pages/second/index.vue': {
      routes:
        | '/second/'
      views:
        | never
    }
    'src/pages/sublayout.vue': {
      routes:
        | '/sublayout'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
