catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - examples/*
catalog:
  '@antfu/eslint-config': ^7.4.3
  '@types/debug': ^4.1.12
  '@types/node': ^25.3.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/compiler-sfc': ^3.5.28
  '@vue/server-renderer': ^3.5.28
  '@vueuse/head': ^2.0.0
  cross-env: ^10.1.0
  debug: ^4.4.3
  eslint: ^10.0.1
  fast-glob: ^3.3.3
  nodemon: ^3.1.14
  tsdown: ^0.20.3
  typescript: ^5.9.3
  unplugin-vue-markdown: ^29.2.0
  unplugin-vue-router: ^0.19.0
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-pages: ^0.33.3
  vite-ssg: ^28.3.0
  vue: ^3.5.28
  vue-router: ^5.0.3
onlyBuiltDependencies:
  - esbuild
