catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - 'examples/*'

catalog:
  '@antfu/eslint-config': ^7.0.1
  '@types/debug': ^4.1.12
  '@types/node': ^25.0.9
  '@vitejs/plugin-vue': ^6.0.3
  '@vue/compiler-sfc': ^3.5.26
  '@vue/server-renderer': ^3.5.26
  '@vueuse/head': ^2.0.0
  cross-env: ^10.1.0
  debug: ^4.4.3
  eslint: ^9.39.2
  fast-glob: ^3.3.3
  nodemon: ^3.1.11
  tsdown: ^0.19.0
  typescript: ^5.9.3
  unplugin-vue-markdown: ^29.2.0
  unplugin-vue-router: ^0.19.0
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-pages: ^0.33.2
  vite-ssg: ^28.2.2
  vue: ^3.5.26
  vue-router: ^4.6.4

onlyBuiltDependencies:
  - esbuild
