catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - 'examples/*'

catalog:
  '@antfu/eslint-config': ^6.4.2
  '@types/debug': ^4.1.12
  '@types/node': ^24.10.1
  cross-env: ^10.1.0
  debug: ^4.4.3
  eslint: ^9.39.1
  fast-glob: ^3.3.3
  tsdown: ^0.17.0
  typescript: ^5.9.3
  vite: ^7.2.6
  vue: ^3.5.25
  vue-router: ^4.6.3

onlyBuiltDependencies:
  - esbuild
