catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - 'examples/*'

overrides:
  typescript: 'catalog:'
  vite: 'catalog:'

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@types/debug': ^4.1.13
  '@types/node': ^26.0.1
  '@vitejs/plugin-vue': ^6.0.7
  '@vue/compiler-sfc': ^3.5.39
  '@vue/server-renderer': ^3.5.39
  '@vueuse/head': ^2.0.0
  cross-env: ^10.1.0
  debug: ^4.4.3
  eslint: ^10.6.0
  fast-glob: ^3.3.3
  nodemon: ^3.1.14
  tsdown: ^0.22.3
  typescript: ^6.0.3
  unplugin-vue-markdown: ^32.0.0
  vite: ^8.1.2
  vite-plugin-inspect: ^11.4.1
  vite-ssg: ^28.3.0
  vitest: ^4.1.9
  vue: ^3.5.39
  vue-router: ^5.1.0

onlyBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - vite@8.1.2

allowBuilds:
  esbuild: true
