/* eslint-disable */
/* prettier-ignore */
// Generated by vite-plugin-vue-layouts-next. Do not edit.
export {}

declare module 'vite-plugin-vue-layouts-next/runtime' {
  interface LayoutRegistry {
    "admin": unknown
    "api-client-layout": unknown
    "default": unknown
    "module1layout": unknown
    "module2layout": unknown
    "second": unknown
    "some-other-thing": unknown
    "sub-layoutsub": unknown
    "thing": unknown
  }
}
