/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'name-override': RouteRecordInfo<
      'name-override',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'who-me-override': RouteRecordInfo<
      'who-me-override',
      '/about/who/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-client-layout': RouteRecordInfo<
      '/api-client-layout',
      '/api-client-layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/module1': RouteRecordInfo<
      '/module1',
      '/module1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/module2': RouteRecordInfo<
      '/module2',
      '/module2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news': RouteRecordInfo<
      '/news',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | '/news/'
      | 'named-news-page'
    >,
    '/news/': RouteRecordInfo<
      '/news/',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'named-news-page': RouteRecordInfo<
      'named-news-page',
      '/news/Today',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nolayout': RouteRecordInfo<
      '/nolayout',
      '/nolayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/second/': RouteRecordInfo<
      '/second/',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/some-other-thing': RouteRecordInfo<
      '/some-other-thing',
      '/some-other-thing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sublayout': RouteRecordInfo<
      '/sublayout',
      '/sublayout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/thing': RouteRecordInfo<
      '/thing',
      '/thing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'name-override'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/about/index.vue': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about/who/me.vue': {
      routes:
        | 'who-me-override'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/api-client-layout.vue': {
      routes:
        | '/api-client-layout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/module1.vue': {
      routes:
        | '/module1'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/module2.vue': {
      routes:
        | '/module2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/news.vue': {
      routes:
        | '/news'
        | '/news/'
        | 'named-news-page'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/news/index.vue': {
      routes:
        | '/news/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/news/Today.vue': {
      routes:
        | 'named-news-page'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/nolayout.vue': {
      routes:
        | '/nolayout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/second/index.vue': {
      routes:
        | '/second/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/some-other-thing.vue': {
      routes:
        | '/some-other-thing'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sublayout.vue': {
      routes:
        | '/sublayout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/thing.vue': {
      routes:
        | '/thing'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
