import type { Logger } from 'vite'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { RUNTIME_ID } from './RouteLayout'

export function resolveDtsPath(dts: boolean | string | undefined, root: string): string | undefined {
  if (!dts)
    return undefined
  return resolve(root, dts === true ? 'layouts.d.ts' : dts)
}

export function createDtsCode(names: string[]): string {
  const entries = [...new Set(names)].sort().map(name => `    ${JSON.stringify(name)}: unknown`)

  return [
    '/* eslint-disable */',
    '/* prettier-ignore */',
    '// Generated by vite-plugin-vue-layouts-next. Do not edit.',
    'export {}',
    '',
    `declare module '${RUNTIME_ID}' {`,
    '  interface LayoutRegistry {',
    ...entries,
    '  }',
    '}',
    '',
  ].join('\n')
}

export async function writeDts(path: string, code: string): Promise<boolean> {
  const current = await readFile(path, 'utf8').catch(() => undefined)
  // Rewriting identical content would still wake up `tsc --watch` and Vite's watcher.
  if (current === code)
    return false

  await mkdir(dirname(path), { recursive: true })
  await writeFile(path, code)
  return true
}

export async function generateDts(path: string, names: string[], logger: Pick<Logger, 'warn'>): Promise<void> {
  try {
    await writeDts(path, createDtsCode(names))
  }
  catch (error) {
    logger.warn(`[vite-plugin-vue-layouts-next] Could not write ${path}: ${(error as Error).message}`)
  }
}
