/* eslint-disable */
/* prettier-ignore */
// Generated by vite-plugin-vue-layouts-next. Do not edit.
export {}

declare module 'vite-plugin-vue-layouts-next/runtime' {
  interface LayoutRegistry {
    "admin": unknown
    "default": unknown
  }
}
